{"uuid": "f60103a9-1a4b-48b8-874c-dd61cdfc5cdb", "children": ["23f0513d-f4d4-47f1-aa42-b767bda3693a", "355ff95c-3226-485c-94bf-0e91ade779a0", "e8cc90a0-5787-402d-b71b-595f7004c102", "96bfd34b-a184-40f1-bea3-1e05451a558b", "c6df7ddd-6eea-4334-80d1-0f0d5fb40c69", "9594ad7c-1765-49b6-b08d-5e0069d70835", "0f2715b1-4b9c-4b44-abcd-e5df8f87ef98", "541ea78a-bd33-400f-8a6b-300de521ef04"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "TypeError: 'module' object is not callable\n", "trace": "  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\w8345\\.conda\\envs\\pytestAutoApi\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\cases\\app_ui\\android\\conftest.py\", line 8, in app\n    driver = Android_UI_Client()\n             ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\PytestAutoApi\\base\\android\\android_ui_client.py\", line 50, in __init__\n    self.appOperator = appOperator(self.driver, self.appium_hub)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1757582061284, "stop": 1757582069492}], "start": 1757582061284, "stop": 1757582069558}